### ISSUE TITLE
Web pages fail if no webcam

### ISSUE THREAD

**Issue by olilarkin** [Mach1Studios/m1-web-spatialaudioplayer#8]
Demo pages don't work at all if you don't have a web cam available. Would be great if it failed more gracefully and allowed trying the other options

**Comment by Mach1Studios** [comment]
great point, adding a little UI prompt at the minimum

**Comment by Mach1Studios** [comment]
@olilarkin this has been added via [PR-9](https://github.com/Mach1Studios/m1-web-spatialaudioplayer/pull/9) thanks to @snyypi 
and merged to [latest](https://github.com/Mach1Studios/m1-web-spatialaudioplayer/commit/28564f14f631b95391fb3a46bfd1a85b17560b66)
